### ISSUE TITLE
Contribution 

### ISSUE THREAD

**Issue by PavanBilagi** [dronelektron/investment-calculator#1]
Hi 

I am really interested to contribute to your project. 

Are you open to contributions?

**Comment by dronelektron** [comment]
> Hi 
> 
> I am really interested to contribute to your project. 
> 
> Are you open to contributions?

Hello. Sorry for late response... You can fork and do what you want with the project. It's just a pet project, which I don't want to continue developing. Also I'm not interested in contributors :)
